# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8300ac8cee23131320f1fb15269f65f0df6e50bae7e9ea8a10dd1d8c1047a85738744953c2a2769abfb8aa129668fc6f110df7ace1580b8929a2da06144ca847

test:
  secret_key_base: 3e04759feace857dff631f938cdb707fe4a14216bc049e9c90161daf117fb2ff4dd7556864582e75f8c7c8df329591eebbe9688af7c4d688bad77e374f93f0ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
